EnableImagePreviewing: false

themes:
  - name: "base-16-black-metal"
    colors:
      - "#000000"  
      - "#c1c1c1"  
      - "#222222"  
      - "#000000"  
      - "#5f8787" 
      - "#dd9999"  
      - "#a06666"  
      - "#888888"  
      - "#999999"  
      - "#aaaaaa"  
      - "#c1c1c1"  
      - "#333333"  
      - "#5f8787"  
      - "#dd9999"  
      - "#a06666"  
      - "#888888"  
      - "#999999"  
      - "#aaaaaa"  
      - "#c1c1c1"  
      - "#aaaaaa"  
      - "#444444"  
      - "#121212"  
      - "#222222"  
      - "#999999"  
      - "#999999"  
